name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/your-project
            git pull origin master
            
            CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"

            if echo "$CHANGED_FILES" | grep -q "server/"; then
              echo "Changes detected in server, deploying..."
              cd /home/ubuntu/voice-workflow/server
              pnpm install
              pnpm run build
              pm2 restart server
            fi

            if echo "$CHANGED_FILES" | grep -q "client/"; then
              echo "Changes detected in client, deploying..."
              cd /home/ubuntu/voice-workflow/client
              pnpm install
              pnpm run build
              pm2 restart client
            fi

            if echo "$CHANGED_FILES" | grep -q "widget/"; then
              echo "Changes detected in widget, deploying..."
              cd /home/ubuntu/voice-workflow/widget
              pnpm install
              pnpm run build
              pm2 restart widget
            fi
