import { Button, Divider, Flex, Space, Tabs, TabsProps } from 'antd'
import { useState, useCallback } from 'react'
import { updateAgent } from '~/common/apis/api.request'
import { IoWarningOutline } from "react-icons/io5"
import { useLocation } from '@remix-run/react'
import { Agent } from '~/types/agents'
import { BiCopy } from "react-icons/bi";

import InputField from '~/components/ui/InputField'
import OpenModalButton from '~/components/ui/OpenModalButton'
import OptionSelector from '~/components/ui/OptionSelector'
import Slider from '~/components/ui/Slider'
import NumberInput from '~/components/ui/NumberInput'

import KnowledgeBaseDrawer from '../../drawer/KnowledgeBaseDrawer'
import ToolsDrawer from '../../drawer/ToolsDrawer'


const AgentOptions = ({ agentData }: { agentData: Agent }) => {
    const [isOpenKnowledgeBase, setIsOpenKnowledgeBase] = useState(false)
    const [isOpenTools, setIsOpenTools] = useState(false)

    const [contactNumber, setContactNumber] = useState<number | null>(null)
    const [firstMessage, setFirstMessage] = useState(agentData?.firstMessage)
    const [systemPrompt, setSystemPrompt] = useState(agentData?.systemPrompt)
    const [temperature, setTemperature] = useState(agentData?.temperature)

    const hasUnsavedChanges = 
        firstMessage !== agentData?.firstMessage || 
        systemPrompt !== agentData?.systemPrompt || 
        temperature !== agentData?.temperature

    const [loading, setLoading] = useState(false)

    const handleUpdateAgent = useCallback(async () => {
        setLoading(true)
        await updateAgent(agentData.id, firstMessage, systemPrompt, temperature)
        setLoading(false)
    }, [agentData.id, firstMessage, systemPrompt, temperature])

    const items: TabsProps['items'] = [
        { key: '1', label: 'Configure', children:  <ConfigureAgent
            contactNumber={contactNumber}
            setContactNumber={setContactNumber}
            firstMessage={firstMessage}
            setFirstMessage={setFirstMessage}
            systemPrompt={systemPrompt}
            setSystemPrompt={setSystemPrompt}
            temperature={temperature}
            setTemperature={setTemperature}
            hasUnsavedChanges={hasUnsavedChanges}
            handleUpdateAgent={handleUpdateAgent}
            loading={loading}
            setIsOpenKnowledgeBase={setIsOpenKnowledgeBase}
            setIsOpenTools={setIsOpenTools}
        /> },
        { key: '2', label: 'Widget', children: <ConfigureWidget id={agentData?.id}/> },
    ]

    return (
        <div>
            <Tabs className='mx-4 mt-1' defaultActiveKey="1" items={items} />
            <KnowledgeBaseDrawer agentId={agentData.id} open={isOpenKnowledgeBase} setOpen={setIsOpenKnowledgeBase} />
            <ToolsDrawer open={isOpenTools} setOpen={setIsOpenTools} />
        </div>
    )
}

const ConfigureAgent = ({
    contactNumber,
    setContactNumber,
    firstMessage,
    setFirstMessage,
    systemPrompt,
    setSystemPrompt,
    temperature,
    setTemperature,
    hasUnsavedChanges,
    handleUpdateAgent,
    loading,
    setIsOpenKnowledgeBase,
    setIsOpenTools,
}:any) => {
    const { pathname } = useLocation()

    return (
        <Space size="middle" direction="vertical" className="px-1 my-5 h-full w-full">
            <OptionSelector title="Agent Language" desc="Choose the language the agent will communicate in." defaultValue="English" />

            {pathname === "/" && (
                <>
                    <Divider style={{ borderWidth: '1px' }} />
                    <NumberInput value={contactNumber} setValue={setContactNumber} title="Phone number" row={1} desc="The Contact Number used for voice again." />
                </>
            )}

            <Divider style={{ borderWidth: '1px' }} />
            <InputField value={firstMessage} setValue={setFirstMessage} title="First message" row={3} desc="The first message the agent will say. If empty, the agent will wait for the user to start the conversation." />

            <Divider style={{ borderWidth: '1px' }} />
            <InputField value={systemPrompt} setValue={setSystemPrompt} title="System prompt" row={4} desc="The system prompt is used to determine the persona of the agent and the context of the conversation." />

            <Divider style={{ borderWidth: '1px' }} />
            <OptionSelector title="LLM" desc="Select which provider and model to use for the LLM. Currently, the LLM cost is covered by us. In the future," defaultValue="GPT-4o Mini" />

            <Divider style={{ borderWidth: '1px' }} />
            <Slider value={temperature} setValue={setTemperature} title="Temperature" desc="Temperature is a parameter that controls the creativity or randomness of the responses generated by the LLM." />

            <Divider style={{ borderWidth: '1px' }} />
            <OpenModalButton title="Knowledge base" desc="Provide the LLM with domain-specific information to help it answer questions more accurately." button="Add item" setOpen={setIsOpenKnowledgeBase} />

            <Divider style={{ borderWidth: '1px' }} />
            <OpenModalButton title="Tools" desc="Provide the agent with tools it can use to help users." button="Add tool" setOpen={setIsOpenTools} />

            {hasUnsavedChanges && (
                <>
                    <Divider style={{ borderWidth: '1px' }} />
                    <Flex justify="space-between" align="center" className="bg-white border border-gray-300 py-3 px-4 w-full rounded-lg">
                        <Flex gap="small">
                            <IoWarningOutline size={21} />
                            <h1 className="text-sm font-medium">You have unsaved changes</h1>
                        </Flex>
                        <Button color="default" variant="solid" onClick={handleUpdateAgent} loading={loading}>
                            Save
                        </Button>
                    </Flex>
                </>
            )}
        </Space>
    )
}




const ConfigureWidget = ({ id }: { id: string }) => {
  const [copied, setCopied] = useState(false);

  const scriptCode = `<script
  async
  id="voice-workflow-chat-widget"
  src="http://localhost:5173/chatWidget.js"
  chatbot-id="${id}"
></script>`;

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(scriptCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy text:", err);
    }
  };

  return (
    <div>
      <h1 className="font-semibold text-gray-900 mb-2">Embedded Code</h1>
      <div className="relative px-4 py-3 bg-gray-100 rounded-md border border-gray-300">
        <pre className="overflow-x-auto text-sm text-gray-800 font-mono">
          <code>{scriptCode}</code>
        </pre>
        <div
          onClick={copyToClipboard}
          className="absolute top-2 right-2 p-1 text-gray-500 hover:text-gray-800 cursor-pointer"
          aria-label="Copy to clipboard"
        >
          <BiCopy/>
        </div>
        {copied && (
          <span className="absolute top-2 right-10 text-xs text-green-500">
            Copied!
          </span>
        )}
      </div>
    </div>
  );
};



export default AgentOptions
