import { Space } from 'antd'
import InputField from '~/components/ui/InputField'
import OpenModalButton from '~/components/ui/OpenModalButton'
import OptionSelector from '~/components/ui/OptionSelector'
import Slider from '~/components/ui/Slider'
import KnowledgeBaseDrawer from '../../drawer/KnowledgeBaseDrawer'
import ToolsDrawer from '../../drawer/ToolsDrawer'
import { useState } from 'react'

const AgentOptions = () => {

    const[isOpenKnowledgeBase,setIsOpenKnowledgeBase] = useState<boolean>(false)
    const[isOpenTools,setIsOpenTools] = useState<boolean>(false)


    return (<>
        <Space size='middle' direction="vertical" className='px-1 my-5'>

            <OptionSelector title='Agent Language' desc='Choose the language the agent will communicate in.' defaultValue='English' />

            <InputField value="Hi, I'm Matilda. What shall we cover today?" title='First message' row={3} desc='The first message the agent will say. If empty, the agent will wait for the user to start the conversation.' />

            <InputField value="You are a mathematics tutor named Matilda. Answer in 3 to 7 sentences in most cases. Ensure that you answer in a way which can be read aloud, so please write your answers in full english." title='System prompt' row={4} desc='The system prompt is used to determine the persona of the agent and the context of the conversation.' />

            <OptionSelector title='LLM' desc='Select which provider and model to use for the LLM.Currently, the LLM cost is covered by us. In the future,' defaultValue='GPT-4o Mini' />
        
            <Slider title='Temperature' desc='Temperature is a parameter that controls the creativity or randomness of the responses generated by the LLM.'/>
       
            <OpenModalButton title='Knowledge base' desc='Provide the LLM with domain-specific information to help it answer questions more accurately.' button='Add item' setOpen={setIsOpenKnowledgeBase}/>
        
            <OpenModalButton title='Tools' desc='Provide the agent with tools it can use to help users.' button='Add tool' setOpen={setIsOpenTools}/>
        
        </Space>
    <KnowledgeBaseDrawer open={isOpenKnowledgeBase} setOpen={setIsOpenKnowledgeBase}/>
    <ToolsDrawer open={isOpenTools} setOpen={setIsOpenTools}/>
    </>
    )
}

export default AgentOptions