version: "3.8"
services:
    database:
        container_name: postgresql
        image: postgres
        restart: always
        volumes:
            - ../docs:/docker-entrypoint-initdb.d
        env_file:
            - .env
        ports:
            - "5442:5432"
